// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: grpc/v1/himo/proto/room.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Himo.V1 {
  public static partial class Room
  {
    static readonly string __ServiceName = "himo.v1.Room";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Himo.V1.ContentRequest> __Marshaller_himo_v1_ContentRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Himo.V1.ContentRequest.Parser));
    static readonly grpc::Marshaller<global::Himo.V1.ContentResponse> __Marshaller_himo_v1_ContentResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Himo.V1.ContentResponse.Parser));

    static readonly grpc::Method<global::Himo.V1.ContentRequest, global::Himo.V1.ContentResponse> __Method_GetContent = new grpc::Method<global::Himo.V1.ContentRequest, global::Himo.V1.ContentResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetContent",
        __Marshaller_himo_v1_ContentRequest,
        __Marshaller_himo_v1_ContentResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Himo.V1.RoomReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Room</summary>
    [grpc::BindServiceMethod(typeof(Room), "BindService")]
    public abstract partial class RoomBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Himo.V1.ContentResponse> GetContent(global::Himo.V1.ContentRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Room</summary>
    public partial class RoomClient : grpc::ClientBase<RoomClient>
    {
      /// <summary>Creates a new client for Room</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RoomClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Room that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RoomClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RoomClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RoomClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Himo.V1.ContentResponse GetContent(global::Himo.V1.ContentRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetContent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Himo.V1.ContentResponse GetContent(global::Himo.V1.ContentRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetContent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Himo.V1.ContentResponse> GetContentAsync(global::Himo.V1.ContentRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetContentAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Himo.V1.ContentResponse> GetContentAsync(global::Himo.V1.ContentRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetContent, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RoomClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RoomClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RoomBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetContent, serviceImpl.GetContent).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RoomBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetContent, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Himo.V1.ContentRequest, global::Himo.V1.ContentResponse>(serviceImpl.GetContent));
    }

  }
}
#endregion
